global:
  resolve_timeout: 5m

route:
  receiver: "email-alert"

receivers:
  - name: "email-alert"
    email_configs:
      - to: "dmpochapskyj@gmail.com"
        from: "dmpochapskyj@gmail.com"
        smarthost: "smtp.sendgrid.net:587"
        auth_username: "apikey"
        auth_password: "${SENDGRID_API_KEY}"
