global:
  scrape_interval: 15s
  # How frequently to evaluate rules
  evaluation_interval: 10s

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:        
        - alertmanager:9093            

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'app'
    static_configs:
      - targets: ['app:5000']
